# Generated by Django 6.0.3 on 2026-03-27 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_article_liked_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='liked_by',
        ),
        migrations.RemoveField(
            model_name='article',
            name='likes',
        ),
    ]
